name: Publish Preview Release

on:
  pull_request_review:
    types: [submitted]

permissions: {}

jobs:
  check:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      has-permissions: ${{ steps.checkPermissions.outputs.require-result }}
    steps:
      - name: Check reviewer permissions
        id: checkPermissions
        uses: actions-cool/check-user-permission@v2
        with:
          require: write

  publish:
    needs: check
    if: needs.check.outputs.has-permissions == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm install

      - run: npx pkg-pr-new publish --commentWithSha
